#app configs
API_KEYS:

  TODOIST_API_KEY: "003996cd9a3c509419a9642cefdfe195a6e8d86e"
  GOOGLE_API_KEY: "your google api key"
  OUTLOOK_API_KEY: "your outlook api key"
  OPENAI_API_KEY: "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"

log: True

airflow:
  todoist_job:
    schedule_interval: "30 */1 * * *"
    dag_id: "todoist_etl_job"
    dag_file: "todoist_etl_job.py"
    dag_name: "todoist_etl_job"
    dag_description: "This job extracts data from todoist, load data on mongodb staging, do all needed transformation and load on Postgres DW. "
    dag_start_date: "2023-12-31"
    dag_owner: lucasvittal
    dag_email: lucasvittal2@outlook.com
    dag_retries: 1
    dag_retry_delay: 2

databases:
  
  local_mongodb:

    host: "localhost"
    port: 27017

  postgres:

    
    user:  "postgres"
    password: "1234567890"
    host: '127.0.0.1'
    port: 5432
    driver: "org.postgresql.Driver"